### ISSUE TITLE
Active Line Mode

### ISSUE THREAD

**Issue by sangyoo91** [perak/codemirror#11]
I would love to have this feature, and if it is already implemented, I must be missing it on how to use it here in meteor.

**Comment by perak** [comment]
@sangyoo91 Here we go - update your package and add `styleActiveLine: true` to code mirror options.

**Comment by sangyoo91** [comment]
@perak Thank you for the fast response! However, I am not getting the active line highlighted after the update to 1.2.4 and adding `styleActiveLine: true` to this.

**Comment by perak** [comment]
@sangyoo91 do you have css style for `.CodeMirror-activeline-background` ?

**Comment by sangyoo91** [comment]
@perak 
```
.CodeMirror-activeline-background {
  background: red;
}
```

This is what I have to test it. However, I don't even see the class in the tree of web inspector.

**Comment by sangyoo91** [comment]
@perak Has this been figured out?

**Comment by perak** [comment]
Sorry dude, being super-busy with other things, I'l try tomorrow. In
meantime, please check official codemirror example and see is there any .js
file included which is not included in this package's package.js (try by
installing package locally and include missing files (if any). If you find
a solution just let me know, that will speed up the things.

@perak <https://github.com/perak> Has this been figured out?

—
Reply to this email directly or view it on GitHub
<https://github.com/perak/codemirror/issues/11#issuecomment-126948062>.

**Comment by perak** [comment]
Hey @sangyoo91 

Excuse me for late answer: I just tried and it works for me (!?). Are you sure package is updated to 1.2.4?

And that you have:
```
{
    styleActiveLine: true
}
```
in editor options?

Screenshot is attached.
![works_for_me](https://cloud.githubusercontent.com/assets/5630814/9046324/3343ff70-3a2a-11e5-8885-35e1e58cd39e.png)

**Comment by sangyoo91** [comment]
@perak 

I'm very sorry. I did `meteor update` but didn't check the package version afterwards because the console showed me that it updated to 1.2.4. However, I just double checked and it still remained as 1.2.3. I did a meteor add specifying the version and it worked. Thank you!!

**Comment by perak** [comment]
@sangyoo91 no problem. Glad it worked! Closing this issue.
