### ISSUE TITLE
Please provide a better reactiveVar example

### ISSUE THREAD

**Issue by wreiske** [perak/codemirror#12]
Hello!
I've been trying to the "reactiveVar" working for some time now.. I don't think it's working, or maybe I'm doing something very wrong.

Would you please provide a better example?

I'm confused if I need to do this, 
```
{{> CodeMirror id="sensorData" name="sensorData" options=editorOptions code=sensorData reactiveVar=sensorDataReactive}}
```
Or this
```
{{> CodeMirror id="sensorData" name="sensorData" options=editorOptions reactiveVar=sensorDataReactive}}
```

I'm also confused if I need "getEditorText". Where does "getEditorText" come from? I don't see it anywhere else in any examples. Should this be sensorDataReactive?
```
     "getEditorText": function() {
         return Session.get('sensorDataReactive');
     }
```

If I try to run 
```
Session.set('sensorDataReactive', 'nope');
```
manually, nothing happens.

Please help!

Much appreciated,
Will

**Comment by wreiske** [comment]
Ugh! I figured it out, the reactiveVar needs to be in quotes... sorry,

**Comment by perak** [comment]
Hey @wreiske sorry for my late answer. 

OK, glad you found a solution :+1:
