### ISSUE TITLE
instead of a tab, editor inserts literal spaces.

### ISSUE THREAD

**Issue by whatsdis** [perak/codemirror#18]
so when I do an indentation, on the second line or so it will instead of inserting a tab html element tag, it inserts a space character. This ends up creating a headache for parsing the YAML because it will become invalid. The code looks fine on the screen but the syntax error is saying indentation issue.

What I'm doing is manually highlighting the spaces, deleting it, and tabbing. only then it correctly inserts the tab html element tag. 

Could we fix this please somebody? IT's driving me NUTS!

**Comment by perak** [comment]
@whatsdis there is `indentWithTabs` option. Default is `false`.
