### ISSUE TITLE
Freemarker

### ISSUE THREAD

**Issue by dtodt** [perak/codemirror#23]
Are there any plans to bring the #freemarker mode?

**Comment by perak** [comment]
@dtodt to be honest, I saw #freemarker for the first time just now. And... I don't see what is cool about it? Server-site templating? After blaze, react, angular who does client side rendering and reactivity provided by meteor...

However, input file for meteor kitchen is (less or more) platform independent and implementing other platforms (not only meteor) is possible, but not planned in near future.

**Comment by perak** [comment]
@dtodt ooops! Sorry, previous answer was wrong because I thought it is in another repository (meteor kitchen).

In this repo, your question makes sense. Yes, why not - if there is plugin for codemirror - I'll add it into this package.
