### ISSUE TITLE
How to use commands on doc, such as doc.markText() ?

### ISSUE THREAD

**Issue by keyscores** [perak/codemirror#24]
I'm looking through the documentation, I can't quite see how a commands can be used to manipulate the CodeMirror after it has been created.
Specifically I would like to use:
http://codemirror.net/doc/manual.html#markText

Thanks in advance

**Comment by perak** [comment]
@keyscores I didn't provided that functionality via package, but I need it too in one project, so I will implement it (but that will be next week).

If you think you can, please do it and send me a pull request.

**Comment by perak** [comment]
What I think is having global variable CodeMirrors, and when one is created, set CodeMirrors["my_code_mirror_id"]. Then, anywhere in the code we can use CodeMirrors["my_code_mirror_id"].anyCodeMirrorMethod(...).

If you got better solution, please let me know.

**Comment by keyscores** [comment]
Thanks! I have a lot to learn before I can contribute.

I've forked your code, and I'm trying to get familiar with CodeMirror itself. I'm having trouble duplicating some examples from the codemirror docs.

For example, in your code, lib/component/component.js line 6, one could insert:

`editor.markText({line: 0, ch: 0}, {line: 9, ch: 0}, {css: "background-color: red"});`

However, I don't see any changes. Why is this?

**Comment by perak** [comment]
OK, I fixed this issue (Added `CodeMirrors` global variable). Testing... will publish code in few (tenths) of minutes...

**Comment by keyscores** [comment]
Great! As a suggestion, maybe call it CodeMirrorEditor, so that you have option of also having CodeMirrorDoc.

**Comment by perak** [comment]
OK, deployed. See `CodeMirrors` global variable (and please let me know did you succeed).

**Comment by perak** [comment]
v1.3.1

**Comment by 0o-de-lally** [comment]
Great let me check it out. How would you suggest I test the example I sent you?

**Comment by perak** [comment]
Anywhere in the program (of course, after your editor is initialised), do `CodeMirrors["id_you_supplied_as_argument_to_codemirror_template"].markText(....)`

**Comment by perak** [comment]
If you got this: `{{> CodeMirror id="some-id" name="someName" options=editorOptions code=editorCode reactiveVar="varName"}}` then access it like this: `CodeMirrors["some-id"].markText(...)`

**Comment by 0o-de-lally** [comment]
Ok cool, let me try that. I personally would prefer a different name the CodeMirrors to avoid confusion. Thanks again!

**Comment by perak** [comment]
Better "CodeMirrors" than nothing. :P

Please close this issue if it works as expected.

**Comment by 0o-de-lally** [comment]
Ok let me test :)

**Comment by 0o-de-lally** [comment]
That's great! It works! Thanks again...

**Comment by perak** [comment]
Glad it worked! :+1:

I need it but was too lazy to implement it, now I'm happy too! 👯

**Comment by 0o-de-lally** [comment]
Very fast turnaround, I'm impressed :)
