### ISSUE TITLE
How to use LINT with your package

### ISSUE THREAD

**Issue by tomitrescak** [perak/codemirror#5]
Great work on the package!
Just wondering how to use lint with your package, there is not much online I could find.

Thanks

**Comment by perak** [comment]
Hi Tomas,

to enable lint you can pass following parameters to editor:

```
{
	lineNumbers: true,
	mode: "javascript",
	gutters: ["CodeMirror-lint-markers"],
	lint: true
}
```

**Comment by perak** [comment]
And example for json:

```
{
	lineNumbers: true,
	mode: "application/ld+json",
	gutters: ["CodeMirror-lint-markers"],
	lint: true
}
```

**Comment by tomitrescak** [comment]
Thanks!! Great. And by any chance do you also know how can I pass options to the linter ? I need to pass silently global variables and turn on strict mode.

**Comment by tomitrescak** [comment]
Ok, got it, simples:

```javascript
editorOptions: function() {
    return {
      lineNumbers: true,
      mode: 'javascript',
      theme: 'midnight',
      gutters: ["CodeMirror-lint-markers"],
      lint: {
        globalstrict: true,
        strict: false
      }
    };
  }
```

**Comment by perak** [comment]
:+1:

**Comment by whatsdis** [comment]
I really badly need to add lint support for YAML how can I achieve this please assist.

**Comment by perak** [comment]
@whatsdis I'l see what I can do. Expect some answers in a hour.

**Comment by whatsdis** [comment]
thank you perak!

**Comment by perak** [comment]
@whatsdis hey dude, I tried with no success :(

yaml-lint requires external jsyaml library to work properly, I added it but it just doesn't work. 
Sorry. I'm busy with other things so I can't dive more into this.

This is what I tried, maybe you can play little bit with this:

into `package.js` add `yaml-lint.js`:

```
api.add_files('lib/codemirror/addon/lint/yaml-lint.js', "client");
```
in your codemirror config, add mode `text/x-yaml`:

```
{
  lineNumbers: true,
  gutters: ["CodeMirror-lint-markers"],
  lint: true,
  mode: "text/x-yaml"
}
```
(with this mode, you'l get syntax highlighting, but lint doesn't work - it shows error in browser console)

Now, reviewing `yaml-lint.js` source code, it says in comments:

```
// Depends on js-yaml.js from https://github.com/nodeca/js-yaml
// declare global: jsyaml
``` 

There is atmosphere package that exposes jsyaml:

```
pntbr:js-yaml-client
```
I added this package to project, and it properly exposes `jsyaml` to client. Then I tried to use package in perak:codemirror by adding into `package.js`:

```
api.use("pntbr:js-yaml-client", "client")
```
No success...

I wish if I can help more. :(

**Comment by perak** [comment]
@whatsdis thanks to @andykingking it works now (v1.2.8)

**Comment by perak** [comment]
To enable yaml linting you need to set (at least) this options:

```
{
  gutters: ["CodeMirror-lint-markers"],
  lint: true,
  mode: "text/x-yaml"
}
```

**Comment by whatsdis** [comment]
@perak, so how do I update the package and where do I set that config?

**Comment by whatsdis** [comment]
thank you @andykingking

**Comment by perak** [comment]
@whatsdis 

- to update package: you can just `meteor remove perak:codemirror` and `meteor add perak:codemirror`

- set options where you normally pass options to codemirror, see README.md, `editorOptions` helper:

```
Template.EditorPage.helpers({

    "editorOptions": function() {
        return {
          gutters: ["CodeMirror-lint-markers"],
          lint: true,
          mode: "text/x-yaml"
        }
    },

    "editorCode": function() {
        return "Code to show in editor";
    }

});
```

**Comment by perak** [comment]
@whatsdis btw, you can build example meteor application using codemirror with http://www.meteorkitchen.com generator. 

Two "kitchen" example apps are using codemirror:

http://generator-ide.meteor.com
http://generator-markdowned.meteor.com

Examples are here:
http://www.meteorkitchen.com/examples

:)

**Comment by whatsdis** [comment]
it works beautifully!

**Comment by perak** [comment]
:+1:

**Comment by andykingking** [comment]
:+1: 
Thanks @perak for the package and for handling the above questions so well.
