### ISSUE TITLE
How to use reactiveVar with your package

### ISSUE THREAD

**Issue by krawalli** [perak/codemirror#6]
Cannot get it running:

´´´javascript
<template name="EditorPage">
    {{> CodeMirror id="someId" name="someName" options=editorOptions reactiveVar='code'}}
</template>
´´´

gives me in console: "Exception from Tracker afterFlush function: Cannot read property 'reactiveVar' of undefined"
--> editor.setValue(Session.get(this.data.reactiveVar));

**Comment by perak** [comment]
Hi,

It was a bug. Fixed now. Just update your package to version 1.2.1.

Enjoy! :)
